name: Build and Push

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: 0.0.9
  GO_VERSION: 1.17

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

      # test application
    - name: Test go app
      run: make test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

      # build app
    - name: Build go app
      run: make build

      # login against docker registry
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    # Build Docker image (don't push on PR)
    - name: Build Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker build -t ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .

    # Push Docker image (don't push on PR)
    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # runs reflux script which updates flux image policy with current image tag
    # and checks deployment status by polling reflux status endpoint
    - name: run reflux script
      run: ./reflux.sh -t ${{ env.VERSION }} -s ${{ secrets.REFLUX_TOKEN }} -n ${{ secrets.REFLUX_NONCE }}
